flags: {}
extra-package-dbs: []
packages:
- .
extra-deps: [deepseq-1.4.4.0, stm-2.5.0.0, binary-0.8.7.0, bytestring-0.10.8.2, containers-0.6.1.1, pretty-1.1.3.6,
  directory-1.3.3.2, unix-2.7.2.2, time-1.8.0.4, Stack-0.4.0, algebraic-graphs-0.4, cond-0.4.1.1]
resolver: lts-12.6
